repository:
  # See https://developer.github.com/v3/repos/#edit for all available settings.

  # The name of the repository. Changing this will rename the repository
  name: material

  # A short description of the repository that will show up on GitHub
  description: Simple Material Design components for the web. No deep shit!

  # A URL with more information about the repository
  homepage:

  # A comma-separated list of topics to set on the repository
  topics: material-design, material, web

  # Either `true` to make the repository private, or `false` to make it public.
  private: true

  # Either `true` to enable issues for this repository, `false` to disable them.
  has_issues: true

  # Either `true` to enable the wiki for this repository, `false` to disable it.
  has_wiki: false

  # Either `true` to enable downloads for this repository, `false` to disable them.
  has_downloads: false

  # Updates the default branch for this repository.
  default_branch: develop

  # Either `true` to allow squash-merging pull requests, or `false` to prevent
  # squash-merging.
  allow_squash_merge: true

  # Either `true` to allow merging pull requests with a merge commit, or `false`
  # to prevent merging pull requests with merge commits.
  allow_merge_commit: true

  # Either `true` to allow rebase-merging pull requests, or `false` to prevent
  # rebase-merging.
  allow_rebase_merge: true

# Labels: define labels for Issues and Pull Requests
labels:
  - name: Accessibility
    color: 5319E7
  - name: bug
    color: ee0701
  - name: Discussion
    color: 69F0AE
  - name: Documentation
    color: 0088CC
  - name: Feature
    color: 4BB14B
  - name: Hacktoberfest
    color: d93f0b
  - name: has-fix
    color: 777777
  - name: has-pr
    color: 777777
  - name: help-wanted
    color: 128A0C
  - name: Infrastructure
    color: 000000
  - name: meta
    color: 000000
  - name: needs-review
    color: FBCA04
  - name: on-hold
    color: FBCA04
  - name: Question
    color: 69F0AE
  - name: wont-fix
    color: 777777
